"""add deleted_at to documents

Revision ID: 222fedc79b7e
Revises: a5bdf8332262
Create Date: 2026-08-02 01:35:23.601398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222fedc79b7e'
down_revision: Union[str, Sequence[str], None] = 'a5bdf8332262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deleted_at')
    # ### end Alembic commands ###
