"""add text extraction fields to documents

Revision ID: a807d07ab7f3
Revises: 222fedc79b7e
Create Date: 2026-08-03 00:33:10.022178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a807d07ab7f3'
down_revision: Union[str, Sequence[str], None] = '222fedc79b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('text_extraction_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_at')
    op.drop_column('documents', 'extraction_error')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'text_extraction_status')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
