"""add embedding_metadata table

Revision ID: ad5728b2f92c
Revises: 8b44cf2eb230
Create Date: 2026-08-04 12:04:46.071237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5728b2f92c'
down_revision: Union[str, Sequence[str], None] = '8b44cf2eb230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_metadata',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('vector_index', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('vector_index')
    )
    op.create_index(op.f('ix_embedding_metadata_chunk_id'), 'embedding_metadata', ['chunk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_metadata_chunk_id'), table_name='embedding_metadata')
    op.drop_table('embedding_metadata')
    # ### end Alembic commands ###
